# Generated by Django 4.2.6 on 2023-10-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("licenseNumber", models.IntegerField()),
                ("lastname", models.CharField(max_length=255)),
                ("firstname", models.CharField(max_length=255)),
                ("dateOfBirth", models.DateField()),
                ("email", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
                (
                    "category",
                    models.IntegerField(
                        choices=[(1, "Simple"), (2, "Double"), (3, "Triple")], default=1
                    ),
                ),
                ("referee", models.BooleanField()),
                ("manager", models.CharField(max_length=255, null=True)),
                (
                    "director",
                    models.CharField(
                        choices=[
                            ("PRES", "President"),
                            ("SEC", "Secretary"),
                            ("REF", "Referee"),
                            ("MAN", "Manager"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "credentials",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Club"), (3, "Basic")]
                    ),
                ),
            ],
        ),
    ]
