# Generated by Django 4.2.6 on 2023-11-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adherents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255)),
                ("mdp", models.CharField(max_length=255)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("no_licence", models.IntegerField()),
                ("date_naissance", models.DateField()),
                ("genre", models.CharField(max_length=255)),
                (
                    "surclassment",
                    models.IntegerField(
                        choices=[(1, "Simple"), (2, "Double"), (3, "Triple")], default=1
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        choices=[
                            ("PRES", "President"),
                            ("SEC", "Secretary"),
                            ("REF", "Referee"),
                            ("MAN", "Manager"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "habilitation",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Club"), (3, "Basic")]
                    ),
                ),
                ("arbitre", models.BooleanField()),
                ("manager", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                ("des_comp", models.CharField(max_length=255)),
                ("taille", models.CharField(max_length=255)),
                ("prix", models.IntegerField()),
                ("lien_photo", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categorie", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("annee_deb", models.IntegerField()),
                ("annee_fin", models.IntegerField()),
                ("tarif", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=255)),
                ("ville", models.CharField(max_length=255)),
                ("complement", models.CharField(max_length=255)),
                ("remarque", models.CharField(max_length=255)),
                ("ordre", models.IntegerField()),
                (
                    "id_adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Creneaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateField()),
                ("fin", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Equipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("points", models.IntegerField()),
                ("victoires", models.IntegerField()),
                ("defaites", models.IntegerField()),
                ("nulls", models.IntegerField()),
                ("photo", models.CharField(max_length=255)),
                ("club", models.BooleanField()),
                (
                    "id_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Postes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Salles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=255)),
                ("vlle", models.CharField(max_length=255)),
                ("complement", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Telephones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("remarque", models.CharField(max_length=255)),
                ("ordre", models.IntegerField()),
                (
                    "id_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.contacts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matchs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_equipe_a", models.IntegerField()),
                ("score_a", models.IntegerField()),
                ("score_b", models.IntegerField()),
                ("duree", models.DateField()),
                ("nom_equipe_b", models.CharField(max_length=255)),
                (
                    "id_creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.creneaux",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Joue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "idlinux_equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrainements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.creneaux",
                    ),
                ),
                (
                    "id_entraineur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "id_equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entraine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_entraineur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "id_equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("lien_photo", models.CharField(max_length=255)),
                ("contenu", models.CharField(max_length=255)),
                ("lien_document", models.CharField(max_length=255)),
                ("date_creation", models.DateField()),
                ("date_validation", models.DateField()),
                (
                    "id_createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "id_equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
                (
                    "id_validateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="creneaux",
            name="id_salle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.salles",
            ),
        ),
        migrations.CreateModel(
            name="Courriels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courriel", models.CharField(max_length=255)),
                ("ordre", models.IntegerField()),
                (
                    "id_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.contacts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Archives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("lien_photo", models.CharField(max_length=255)),
                ("contenu", models.CharField(max_length=255)),
                ("lien_document", models.CharField(max_length=255)),
                ("date_creation", models.DateField()),
                ("date_validation", models.DateField()),
                (
                    "id_createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "id_validateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Arbitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "id_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.matchs",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adherents",
            name="id_categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.categories",
            ),
        ),
        migrations.AddField(
            model_name="adherents",
            name="id_poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.postes",
            ),
        ),
    ]
