# Generated by Django 4.2.7 on 2023-11-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adherents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=255)),
                ("mdp", models.CharField(max_length=255)),
                ("nom", models.CharField(blank=True, max_length=255, null=True)),
                ("prenom", models.CharField(blank=True, max_length=255, null=True)),
                ("no_licence", models.IntegerField(blank=True, null=True)),
                ("date_naissance", models.DateField()),
                ("genre", models.CharField(max_length=255)),
                (
                    "surclassement",
                    models.IntegerField(
                        choices=[(1, "Simple"), (2, "Double"), (3, "Triple")], default=1
                    ),
                ),
                (
                    "habilitation",
                    models.IntegerField(
                        choices=[(1, "Admin"), (2, "Club"), (3, "Basic")]
                    ),
                ),
                ("arbitre", models.BooleanField()),
                ("entraineur", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Catalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("des_comp", models.CharField(blank=True, max_length=255, null=True)),
                ("taille", models.CharField(blank=True, max_length=255, null=True)),
                ("coloris", models.CharField(blank=True, max_length=255, null=True)),
                ("prix", models.IntegerField(blank=True, null=True)),
                ("lien_photo", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categorie", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("annee_deb", models.IntegerField(blank=True, null=True)),
                ("annee_fin", models.IntegerField(blank=True, null=True)),
                ("tarif", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=255, null=True)),
                ("prenom", models.CharField(blank=True, max_length=255, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "code_postal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("complement", models.CharField(blank=True, max_length=255, null=True)),
                ("remarque", models.CharField(blank=True, max_length=255, null=True)),
                ("ordre", models.IntegerField(blank=True, null=True)),
                (
                    "adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Creneaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateField()),
                ("fin", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Equipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("points", models.IntegerField(null=True)),
                ("victoires", models.IntegerField(null=True)),
                ("defaites", models.IntegerField(null=True)),
                ("nulls", models.IntegerField(null=True)),
                ("photo", models.CharField(max_length=255, null=True)),
                ("club", models.BooleanField()),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Postes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Salles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255, null=True)),
                ("code_postal", models.CharField(max_length=255, null=True)),
                ("ville", models.CharField(max_length=255, null=True)),
                ("complement", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Telephones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("remarque", models.CharField(max_length=255)),
                ("ordre", models.IntegerField()),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.contacts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matchs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_equipe_a", models.IntegerField()),
                ("score_a", models.IntegerField(null=True)),
                ("score_b", models.IntegerField(null=True)),
                ("duree", models.DurationField(null=True)),
                ("nom_equipe_b", models.CharField(max_length=255)),
                (
                    "creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.creneaux",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Joue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrainements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creneau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.creneaux",
                    ),
                ),
                (
                    "entraineur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entraine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.IntegerField(blank=True, null=True)),
                (
                    "entraineur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("lien_photo", models.CharField(blank=True, max_length=255, null=True)),
                ("contenu", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lien_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_creation", models.DateField()),
                ("date_validation", models.DateField(blank=True, null=True)),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.equipes",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="creneaux",
            name="salle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.salles",
            ),
        ),
        migrations.CreateModel(
            name="Courriels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courriel", models.CharField(max_length=255)),
                ("ordre", models.IntegerField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.contacts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Archives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("lien_photo", models.CharField(blank=True, max_length=255, null=True)),
                ("contenu", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lien_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_creation", models.DateField()),
                ("date_validation", models.DateField(blank=True, null=True)),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.adherents",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Arbitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="gestion_adherents.adherents",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_adherents.matchs",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adherents",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.categories",
            ),
        ),
        migrations.AddField(
            model_name="adherents",
            name="poste",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.postes",
            ),
        ),
    ]
