# Generated by Django 4.2.6 on 2023-11-03 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adherents",
            old_name="surclassment",
            new_name="surclassement",
        ),
    ]
