# Generated by Django 4.2.7 on 2023-11-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0002_alter_adherents_login_alter_adherents_mdp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherents",
            name="no_licence",
            field=models.IntegerField(default=99999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adherents",
            name="nom",
            field=models.CharField(default="DEFAULT", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adherents",
            name="prenom",
            field=models.CharField(default="DEFAULT", max_length=255),
            preserve_default=False,
        ),
    ]
