# Generated by Django 4.2.6 on 2023-11-03 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0002_rename_surclassment_adherents_surclassement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adherents",
            old_name="manager",
            new_name="entraineur",
        ),
    ]
