# Generated by Django 4.2.7 on 2023-11-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_adherents",
            "0003_alter_adherents_no_licence_alter_adherents_nom_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchs",
            name="id_equipe_a",
        ),
        migrations.AddField(
            model_name="matchs",
            name="equipe_a",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.equipes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adherents",
            name="no_licence",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="entrainements",
            name="entraineur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.entraine",
            ),
        ),
    ]
