# Generated by Django 4.2.7 on 2023-11-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_adherents",
            "0004_remove_matchs_id_equipe_a_matchs_equipe_a_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="telephones",
            name="ordre",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="telephones",
            name="remarque",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telephones",
            name="type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
