# Generated by Django 4.2.7 on 2023-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_adherents",
            "0004_entraine_ordre_alter_adherents_no_licence_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherents",
            name="no_licence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="adherents",
            name="nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="adherents",
            name="prenom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="archives",
            name="contenu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="archives",
            name="date_validation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="archives",
            name="lien_document",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="archives",
            name="lien_photo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="archives",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="des_comp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="lien_photo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="prix",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="catalogue",
            name="taille",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="annee_deb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="annee_fin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="tarif",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="code_postal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="complement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="ordre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="prenom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="remarque",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="ville",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="courriels",
            name="ordre",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="contenu",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="date_validation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="lien_document",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="lien_photo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="titre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="entraine",
            name="ordre",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
