# Generated by Django 4.2.7 on 2023-11-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_adherents",
            "0005_alter_telephones_ordre_alter_telephones_remarque_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherents",
            name="poste",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.postes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postes",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
