# Generated by Django 4.2.7 on 2023-11-04 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_adherents",
            "0005_alter_adherents_no_licence_alter_adherents_nom_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adherents",
            name="director",
        ),
    ]
