# Generated by Django 4.2.7 on 2023-11-04 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0006_remove_adherents_director"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salles",
            old_name="vlle",
            new_name="ville",
        ),
    ]
