# Generated by Django 4.2.7 on 2023-11-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0007_rename_vlle_salles_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipes",
            name="photo",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
