# Generated by Django 4.2.7 on 2023-11-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0010_alter_equipes_defaites_alter_equipes_victoires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipes",
            name="nulls",
            field=models.IntegerField(null=True),
        ),
    ]
