# Generated by Django 4.2.7 on 2023-11-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0011_alter_equipes_nulls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherents",
            name="id_poste",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_adherents.postes",
            ),
        ),
    ]
