# Generated by Django 4.2.7 on 2023-11-04 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0012_alter_adherents_id_poste"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joue",
            old_name="idlinux_equipe",
            new_name="id_equipe",
        ),
    ]
