# Generated by Django 4.2.7 on 2023-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0013_rename_idlinux_equipe_joue_id_equipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogue",
            name="coloris",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
