# Generated by Django 4.2.7 on 2023-11-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0014_catalogue_coloris"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salles",
            name="complement",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
