# Generated by Django 4.2.7 on 2023-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0015_alter_salles_complement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salles",
            name="adresse",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
