# Generated by Django 4.2.7 on 2023-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0016_alter_salles_adresse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salles",
            name="code_postal",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="salles",
            name="ville",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
