# Generated by Django 4.2.7 on 2023-11-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0017_alter_salles_code_postal_alter_salles_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchs",
            name="duree",
            field=models.DurationField(null=True),
        ),
    ]
