# Generated by Django 4.2.7 on 2023-11-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_adherents", "0018_alter_matchs_duree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchs",
            name="score_a",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="matchs",
            name="score_b",
            field=models.IntegerField(null=True),
        ),
    ]
